console.log(typeof 42); //number
console.log(typeof 'Veinticinco'); //string
console.log(typeof -666); //number
console.log(typeof true); //boolean
console.log(typeof 0); //number
console.log(typeof ''); //String
console.log(typeof null); //null
console.log(typeof undefined); //undefined
console.log(typeof FALSE); //undefined
console.log(typeof "123"); //String